export const routes = {
  ACCESS_POINT: '/',
  ADD_BIRD: '/shkud/birds/add',
  ADD_FAMILY: '/shkud/family/add',
  ADD_ORDER: 'shkud/order/add',
  ADD_NEWS: '/shkud/news/add',
  ADD_USER: '/shkud/user/add',
  ADMIN_ACCESS_POINT: '/shkud',
  ADMIN_DASHBOARD: '/shkud',
  EDIT_ORDER: '/shkud/order/edit/:orderId',
  EDIT_FAMILY: '/shkud/family/edit/:familyId',
  EDIT_BIRD: '/shkud/bird/edit/:birdId',
  EDIT_NEWS: '/shkud/news/edit/:newsId',
  HOME: '/home',
  LIST_BIRDS: '/shkud/birds/list',
  LIST_ORDER: 'shkud/order/list',
  LIST_FAMILIES: 'shkud/family/list',
  LIST_NEWS: '/shkud/news/list',
  LIST_USERS: '/shkud/users',
  LOGIN: '/login',
};
